set_ac_fan_speed:
  fields:
    device_id:
    fan_speed:
      example: "'auto'"

set_attribute:
  fields:
    device_id:
    attribute:
      example: "eco_mode"
    value:
      example: true